// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMqskj4Aq8HarHRVin2by5K7o_TFAZQE',
    appId: '1:961586507345:web:4a850eb6845f82100f9270',
    messagingSenderId: '961586507345',
    projectId: 'automate-appium-class',
    authDomain: 'automate-appium-class.firebaseapp.com',
    storageBucket: 'automate-appium-class.appspot.com',
    measurementId: 'G-X1HNLQE0YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwRiowJa5dA-_e0i7nkCZXd8JSp4zzAs',
    appId: '1:961586507345:android:48d55e21e6a099520f9270',
    messagingSenderId: '961586507345',
    projectId: 'automate-appium-class',
    storageBucket: 'automate-appium-class.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeTnW6LcKd956doYJ-c-dgG1-FCwP8jEo',
    appId: '1:961586507345:ios:82287f0b830be83a0f9270',
    messagingSenderId: '961586507345',
    projectId: 'automate-appium-class',
    storageBucket: 'automate-appium-class.appspot.com',
    iosBundleId: 'com.example.automationAppium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeTnW6LcKd956doYJ-c-dgG1-FCwP8jEo',
    appId: '1:961586507345:ios:82287f0b830be83a0f9270',
    messagingSenderId: '961586507345',
    projectId: 'automate-appium-class',
    storageBucket: 'automate-appium-class.appspot.com',
    iosBundleId: 'com.example.automationAppium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpMqskj4Aq8HarHRVin2by5K7o_TFAZQE',
    appId: '1:961586507345:web:12c858f2cd509b6f0f9270',
    messagingSenderId: '961586507345',
    projectId: 'automate-appium-class',
    authDomain: 'automate-appium-class.firebaseapp.com',
    storageBucket: 'automate-appium-class.appspot.com',
    measurementId: 'G-81MX069848',
  );

}